services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "2665:2665"
    depends_on:
      - db
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "2666:2666"
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    ports:
      - "2667:27017"
    volumes:
      - database:/data/db
volumes:
  database:
